-- ==============================================================================
-- DP10 — assist_dev.cat — Collaboration, Review & Audit Trail
-- Grain: lifecycle chronology event. OIG document production. Pre-award review compliance.
-- ==============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- assist_dev.cat.dim_event_type
-- Lifecycle event type dimension. SCD Type 1. Source: aasbs.lu_event_type.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS assist_dev.cat.dim_event_type
(
    event_type_sk                                  BIGINT GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate key.',
    event_type_cd                                  STRING NOT NULL                COMMENT 'NK — event type code from lu_event_type.',
    event_type_desc                                STRING                         COMMENT 'Event type description.',
    lifecycle_phase_cd                             STRING                         COMMENT 'Lifecycle phase — PRE_AWARD, AWARD, POST_AWARD, CLOSEOUT.',
    is_system_event_flag                           BOOLEAN                        COMMENT 'TRUE if generated by system; FALSE if user-initiated.',
    is_audit_significant                           BOOLEAN                        COMMENT 'TRUE if this event type is significant for OIG/audit purposes.',
    _gold_created_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was first created by the pipeline.',
    _gold_updated_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was last updated by the pipeline.',
    _source_batch_id                               STRING                         COMMENT 'Databricks job_run_id of pipeline run that last wrote this row.'
)
USING DELTA
CLUSTER BY (event_type_sk, event_type_cd)
COMMENT 'Lifecycle event type dimension. SCD Type 1. Source: aasbs.lu_event_type.'
TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.minReaderVersion' = '1',
    'delta.minWriterVersion' = '4',
    'pipeline.layer' = 'gold',
    'pipeline.catalog' = 'assist_catalog',
    'pipeline.schema' = 'cat',
    'pipeline.table' = 'dim_event_type',
    'scd.type' = '1',
    'pipeline.data_product' = 'DP10'
);

-- ────────────────────────────────────────────────────────────────────────────
-- assist_dev.cat.dim_review_type
-- Pre-award review type dimension. SCD Type 1. Sources: aasbs.lu_review_type.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS assist_dev.cat.dim_review_type
(
    review_type_sk                                 BIGINT GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate key.',
    review_type_cd                                 STRING NOT NULL                COMMENT 'NK — review type code.',
    review_type_desc                               STRING                         COMMENT 'Review type description — Legal, Technical, Price, OIG.',
    is_pre_award_flag                              BOOLEAN                        COMMENT 'TRUE if this review type applies pre-award.',
    is_mandatory_flag                              BOOLEAN                        COMMENT 'TRUE if this review type is mandatory per GSA policy.',
    far_basis                                      STRING                         COMMENT 'FAR clause or policy basis for this review requirement.',
    _gold_created_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was first created by the pipeline.',
    _gold_updated_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was last updated by the pipeline.',
    _source_batch_id                               STRING                         COMMENT 'Databricks job_run_id of pipeline run that last wrote this row.'
)
USING DELTA
CLUSTER BY (review_type_sk, review_type_cd)
COMMENT 'Pre-award review type dimension. SCD Type 1. Sources: aasbs.lu_review_type.'
TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.minReaderVersion' = '1',
    'delta.minWriterVersion' = '4',
    'pipeline.layer' = 'gold',
    'pipeline.catalog' = 'assist_catalog',
    'pipeline.schema' = 'cat',
    'pipeline.table' = 'dim_review_type',
    'scd.type' = '1',
    'pipeline.data_product' = 'DP10'
);

-- ────────────────────────────────────────────────────────────────────────────
-- assist_dev.cat.dim_reviewer_type
-- Reviewer type dimension. SCD Type 1. Source: aasbs.lu_reviewer_type.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS assist_dev.cat.dim_reviewer_type
(
    reviewer_type_sk                               BIGINT GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate key.',
    reviewer_type_cd                               STRING NOT NULL                COMMENT 'NK — reviewer type code.',
    reviewer_type_desc                             STRING                         COMMENT 'Reviewer type description — Primary, Secondary, Approval.',
    _gold_created_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was first created by the pipeline.',
    _gold_updated_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was last updated by the pipeline.',
    _source_batch_id                               STRING                         COMMENT 'Databricks job_run_id of pipeline run that last wrote this row.'
)
USING DELTA
CLUSTER BY (reviewer_type_sk, reviewer_type_cd)
COMMENT 'Reviewer type dimension. SCD Type 1. Source: aasbs.lu_reviewer_type.'
TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.minReaderVersion' = '1',
    'delta.minWriterVersion' = '4',
    'pipeline.layer' = 'gold',
    'pipeline.catalog' = 'assist_catalog',
    'pipeline.schema' = 'cat',
    'pipeline.table' = 'dim_reviewer_type',
    'scd.type' = '1',
    'pipeline.data_product' = 'DP10'
);

-- ────────────────────────────────────────────────────────────────────────────
-- assist_dev.cat.dim_finding
-- Review finding dimension. SCD Type 1. Source: aasbs.lu_review_finding.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS assist_dev.cat.dim_finding
(
    finding_sk                                     BIGINT GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate key.',
    finding_cd                                     STRING NOT NULL                COMMENT 'NK — review finding code.',
    finding_desc                                   STRING                         COMMENT 'Finding description — Approved, Approved with Comments, Returned, etc.',
    is_blocking_flag                               BOOLEAN                        COMMENT 'TRUE if this finding blocks progression to next lifecycle phase.',
    requires_remediation                           BOOLEAN                        COMMENT 'TRUE if remediation action is required.',
    _gold_created_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was first created by the pipeline.',
    _gold_updated_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was last updated by the pipeline.',
    _source_batch_id                               STRING                         COMMENT 'Databricks job_run_id of pipeline run that last wrote this row.'
)
USING DELTA
CLUSTER BY (finding_sk, finding_cd)
COMMENT 'Review finding dimension. SCD Type 1. Source: aasbs.lu_review_finding.'
TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.minReaderVersion' = '1',
    'delta.minWriterVersion' = '4',
    'pipeline.layer' = 'gold',
    'pipeline.catalog' = 'assist_catalog',
    'pipeline.schema' = 'cat',
    'pipeline.table' = 'dim_finding',
    'scd.type' = '1',
    'pipeline.data_product' = 'DP10'
);

-- ────────────────────────────────────────────────────────────────────────────
-- assist_dev.cat.fact_lifecycle_event
-- Grain  : Lifecycle event (source_chronology_id / source_collab_id) — one row per event
-- Lifecycle event fact — every key acquisition event with timestamp and user. Feeds OIG audit trail an
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS assist_dev.cat.fact_lifecycle_event
(
    lifecycle_event_sk                             BIGINT GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate key.',
    event_type_sk                                  BIGINT NOT NULL                COMMENT 'FK to cat.dim_event_type.',
    entity_type_sk                                 BIGINT NOT NULL                COMMENT 'FK to wpr.dim_entity_type — entity this event applies to.',
    award_sk                                       BIGINT                         COMMENT 'FK to common.dim_award (when event relates to award).',
    ia_sk                                          BIGINT                         COMMENT 'FK to common.dim_ia (when event relates to IA).',
    agency_sk                                      BIGINT                         COMMENT 'FK to common.dim_agency.',
    event_date_sk                                  INT                            COMMENT 'FK to common.dim_date — event timestamp date.',
    source_entity_id                               BIGINT NOT NULL                COMMENT 'Source entity primary key.',
    source_chronology_id                           BIGINT                         COMMENT 'Source aasbs.chronology.id.',
    source_collab_id                               BIGINT                         COMMENT 'Source aasbs.central_collab.id (when collab event).',
    event_timestamp                                TIMESTAMP                      COMMENT 'Precise event timestamp.',
    event_user_id                                  STRING                         COMMENT 'ASSIST user who triggered event.',
    event_description                              STRING                         COMMENT 'Event description text.',
    collab_type_cd                                 STRING                         COMMENT 'Collaboration type code (collab events only).',
    collab_status_cd                               STRING                         COMMENT 'Collaboration status at time of event.',
    collab_due_dt                                  TIMESTAMP                      COMMENT 'Collaboration due date.',
    comment_type_cd                                STRING                         COMMENT 'Comment type code (comment events only).',
    comment_text                                   STRING                         COMMENT 'Comment text — redacted for PII in Gold (full text in Silver).',
    email_status_cd                                STRING                         COMMENT 'Email status code (email events only).',
    _gold_created_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was first created by the pipeline.',
    _gold_updated_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was last updated by the pipeline.',
    _source_batch_id                               STRING                         COMMENT 'Databricks job_run_id of pipeline run that last wrote this row.'
)
USING DELTA
CLUSTER BY (source_entity_id, event_date_sk)
COMMENT 'Lifecycle event fact — every key acquisition event with timestamp and user. Feeds OIG audit trail and process mining. Sources: aasbs.chronology, central_collab, central_comment, email_log.'
TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.minReaderVersion' = '1',
    'delta.minWriterVersion' = '4',
    'pipeline.layer' = 'gold',
    'pipeline.catalog' = 'assist_catalog',
    'pipeline.schema' = 'cat',
    'pipeline.table' = 'fact_lifecycle_event',
    'pipeline.data_product' = 'DP10',
    'pipeline.consumer' = 'OIG, Compliance, Legal Counsel'
);

-- ────────────────────────────────────────────────────────────────────────────
-- assist_dev.cat.fact_review_determination
-- Grain  : Review determination (source_determination_id) — one row per reviewer determination
-- Pre-award review determination fact — reviewer decisions with findings and determination timelines. 
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS assist_dev.cat.fact_review_determination
(
    review_determination_sk                        BIGINT GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate key.',
    review_type_sk                                 BIGINT NOT NULL                COMMENT 'FK to cat.dim_review_type.',
    reviewer_type_sk                               BIGINT NOT NULL                COMMENT 'FK to cat.dim_reviewer_type.',
    finding_sk                                     BIGINT                         COMMENT 'FK to cat.dim_finding.',
    award_sk                                       BIGINT                         COMMENT 'FK to common.dim_award.',
    ia_sk                                          BIGINT                         COMMENT 'FK to common.dim_ia.',
    agency_sk                                      BIGINT NOT NULL                COMMENT 'FK to common.dim_agency.',
    review_date_sk                                 INT                            COMMENT 'FK to common.dim_date — determination date.',
    source_review_id                               BIGINT NOT NULL                COMMENT 'Source aasbs.review.id.',
    source_determination_id                        BIGINT                         COMMENT 'Source aasbs.review_determination.id.',
    reviewer_user_id                               STRING                         COMMENT 'Reviewer ASSIST user ID.',
    review_assigned_dt                             TIMESTAMP                      COMMENT 'Date review was assigned to reviewer.',
    determination_dt                               TIMESTAMP                      COMMENT 'Date determination was made.',
    days_to_determination                          INT                            COMMENT 'Calendar days from assignment to determination.',
    determination_comments                         STRING                         COMMENT 'Reviewer determination comments.',
    is_blocking_finding_flag                       BOOLEAN                        COMMENT 'TRUE if finding blocked progression.',
    _gold_created_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was first created by the pipeline.',
    _gold_updated_at                               TIMESTAMP                      COMMENT 'Timestamp this Gold row was last updated by the pipeline.',
    _source_batch_id                               STRING                         COMMENT 'Databricks job_run_id of pipeline run that last wrote this row.'
)
USING DELTA
CLUSTER BY (source_review_id, review_date_sk)
COMMENT 'Pre-award review determination fact — reviewer decisions with findings and determination timelines. Sources: aasbs.review, aasbs.review_determination.'
TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.minReaderVersion' = '1',
    'delta.minWriterVersion' = '4',
    'pipeline.layer' = 'gold',
    'pipeline.catalog' = 'assist_catalog',
    'pipeline.schema' = 'cat',
    'pipeline.table' = 'fact_review_determination',
    'pipeline.data_product' = 'DP10'
);

-- ────────────────────────────────────────────────────────────────────────────
-- VIEW: assist_dev.cat.v_pre_award_review_compliance
-- Pre-award review compliance view — mandatory review completion rates, determination timelines, and b
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW assist_dev.cat.v_pre_award_review_compliance
COMMENT 'Pre-award review compliance view — mandatory review completion rates, determination timelines, and blocking findings by review type. Supports FAR 1.602-1 compliance tracking.'
AS
SELECT
    ag.agency_name, ia.ia_num, aw.award_piid,
    rt.review_type_desc, rt.is_mandatory_flag,
    d.federal_fiscal_fy,
    COUNT(f.review_determination_sk)                     AS total_reviews,
    AVG(f.days_to_determination)                         AS avg_days_to_determination,
    SUM(CASE WHEN fi.is_blocking_flag THEN 1 ELSE 0 END) AS blocking_findings,
    SUM(CASE WHEN f.is_blocking_finding_flag THEN 1 ELSE 0 END) AS awards_blocked
FROM assist_dev.cat.fact_review_determination f
JOIN assist_dev.cat.dim_review_type   rt ON f.review_type_sk   = rt.review_type_sk
JOIN assist_dev.cat.dim_finding       fi ON f.finding_sk       = fi.finding_sk
JOIN assist_dev.common.dim_agency     ag ON f.agency_sk        = ag.agency_sk  AND ag.is_current_flag
JOIN assist_dev.common.dim_ia         ia ON f.ia_sk            = ia.ia_sk      AND ia.is_current_flag
JOIN assist_dev.common.dim_award      aw ON f.award_sk         = aw.award_sk   AND aw.is_current_flag
JOIN assist_dev.common.dim_date       d  ON f.review_date_sk   = d.date_sk
GROUP BY ALL;

-- ────────────────────────────────────────────────────────────────────────────
-- VIEW: assist_dev.cat.v_event_timeline
-- Full event timeline view — chronologically ordered lifecycle events per entity with phase labels. Pr
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW assist_dev.cat.v_event_timeline
COMMENT 'Full event timeline view — chronologically ordered lifecycle events per entity with phase labels. Primary OIG document production view.'
AS
SELECT
    et.lifecycle_phase_cd,
    et.event_type_desc,
    ia.ia_num,
    aw.award_piid,
    ag.agency_name,
    d.calendar_date         AS event_date,
    f.event_timestamp,
    f.event_user_id,
    f.event_description,
    f.collab_type_cd,
    f.collab_status_cd,
    f.email_status_cd
FROM assist_dev.cat.fact_lifecycle_event f
JOIN assist_dev.cat.dim_event_type   et ON f.event_type_sk  = et.event_type_sk
JOIN assist_dev.common.dim_agency    ag ON f.agency_sk      = ag.agency_sk AND ag.is_current_flag
JOIN assist_dev.common.dim_date      d  ON f.event_date_sk  = d.date_sk
LEFT JOIN assist_dev.common.dim_ia   ia ON f.ia_sk          = ia.ia_sk     AND ia.is_current_flag
LEFT JOIN assist_dev.common.dim_award aw ON f.award_sk      = aw.award_sk  AND aw.is_current_flag
ORDER BY f.source_entity_id, f.event_timestamp;
